apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-1
    app.kubernetes.io/part-of: kafka
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
    io.kompose.service: kafka-broker-1
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-broker-1
    spec:
      serviceAccountName: runasroot
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - zookeeper
            - "2181"
            - "1"
            - kafka-broker-1
            - "9091"
          env:
            - name: PROM_AGENT_PORT
              value: "1123"
          image: ' '
          name: kafka-broker-1
          ports:
            - containerPort: 9091
            - containerPort: 19091
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/logs
              name: kafka-data
      restartPolicy: Always
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - kafka-broker-1
        from:
          kind: ImageStreamTag
          namespace: task-manager
          name: kafka:base
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
