apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-3
  name: kafka-broker-3
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
    - name: "19093"
      port: 19093
      targetPort: 19093
    - name: "1123"
      port: 1123
      targetPort: 1123
  selector:
    io.kompose.service: kafka-broker-3
status:
  loadBalancer: {}
