apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ksql
    app.kubernetes.io/part-of: kafka
  name: ksql
spec:
  replicas: 1
  selector:
    io.kompose.service: ksql
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql
    spec:
      serviceAccountName: runasroot
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - zookeeper
            - "2181"
            - kafka-broker-1:9091, kafka-broker-2:9092, kafka-broker-3:9093
            - schemaregistry
            - "8081"
          env:
            - name: KAFKA_CONNECT_HOST
              value: kafkaconnect
            - name: KAFKA_CONNECT_PORT
              value: "8083"
            - name: KAFKA_CONNECT_PROT
              value: http
          image: ' '
          name: ksql
          ports:
            - containerPort: 8088
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ksql
        from:
          kind: ImageStreamTag
          name: kafka:ksql
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
