apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
    app.kubernetes.io/part-of: idp
  name: openldap
spec:
  replicas: 1
  selector:
    io.kompose.service: openldap
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openldap
    spec:
      serviceAccountName: runasroot
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - --copy-service
          env:
            - name: LDAP_ADMIN_PASSWORD
              value: Ladm1234!
            - name: LDAP_DOMAIN
              value: corp.com
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              value: The Corporation
            - name: TZ
              value: Europe/Istanbul
          image: ' '
          name: openldap
          ports:
            - containerPort: 389
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - openldap
        from:
          kind: ImageStreamTag
          namespace: task-manager
          name: openldap:1.3.0
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
