apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: schemaregistry
    app.kubernetes.io/part-of: kafka
  name: schemaregistry
spec:
  replicas: 1
  selector:
    io.kompose.service: schemaregistry
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: schemaregistry
    spec:
      serviceAccountName: runasroot
      securityContext:
        runAsUser: 0
      containers:
        - args:
            - zookeeper
            - "2181"
            - avro-schema-topic
            - PLAINTEXT:\/\/kafka-broker-1:9091, PLAINTEXT:\/\/kafka-broker-2:9092, PLAINTEXT:\/\/kafka-broker-3:9093
          env:
            - name: DEPS
              value: zookeeper:2181,kafka-broker-1:9091, kafka-broker-2:9092, kafka-broker-3:9093
          image: ' '
          name: schemaregistry
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - schemaregistry
        from:
          kind: ImageStreamTag
          namespace: task-manager
          name: kafka:schemaregistry
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
