{
 "title": "Kafka Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ingress Message Count per Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total"
    }
   ]
  },
  {
   "title": "Ingress Message Count per Broker",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{topic=\"tasks\"}"
    }
   ]
  },
  {
   "title": "Memory (heap) Usage of Brokers",
   "type": "stat",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=~\"zookeeper:1123|kafka-broker-1:1123|kafka-broker-2:1123|kafka-broker-3:1123\"}"
    }
   ]
  }
 ]
}