apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-2
  name: kafka-broker-2
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "19092"
      port: 19092
      targetPort: 19092
  selector:
    io.kompose.service: kafka-broker-2
status:
  loadBalancer: {}
