apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-2
  name: kafka-broker-2
spec:
  replicas: 1
  selector:
    io.kompose.service: kafka-broker-2
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-broker-2
    spec:
      containers:
        - args:
            - zookeeper
            - "2181"
            - "2"
            - kafka-broker-2
            - "9092"
          env:
            - name: PROM_AGENT_PORT
              value: "1123"
          image: ' '
          name: kafka-broker-2
          ports:
            - containerPort: 9092
            - containerPort: 19092
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/logs
              name: kafka-data
      restartPolicy: Always
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - kafka-broker-2
        from:
          kind: ImageStreamTag
          name: kafka-broker-2:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
