apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-1
  name: kafka-broker-1
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
    - name: "19091"
      port: 19091
      targetPort: 19091
  selector:
    io.kompose.service: kafka-broker-1
status:
  loadBalancer: {}
