apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    io.kompose.service: keycloak
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: DB_ADDR
              value: idpdb
            - name: DB_DATABASE
              value: idpdb
            - name: DB_PASSWORD
              value: db1234
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: dbuser
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: Kc1234!
            - name: KEYCLOAK_USER
              value: kcadm
          image: ' '
          name: keycloak
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - keycloak
        from:
          kind: ImageStreamTag
          name: keycloak:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
