apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: task-processor
  name: task-processor
spec:
  replicas: 1
  selector:
    io.kompose.service: task-processor
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: task-processor
    spec:
      containers:
        - env:
            - name: BROKER_1
              value: kafka-broker-1:19091
            - name: BROKER_2
              value: kafka-broker-2:19092
            - name: BROKER_3
              value: kafka-broker-3:19093
            - name: DEPS
              value: kafka-broker-1:19091, kafka-broker-2:19092, kafka-broker-3:19093, schemaregistry:8081, keycloak:8080
            - name: IDP_HOST
              value: keycloak
            - name: IDP_PORT
              value: "8080"
            - name: IDP_PROT
              value: http
            - name: SERVER_PORT
              value: "8080"
            - name: SR_HOST
              value: schemaregistry
            - name: SR_PORT
              value: "8081"
            - name: SR_PROT
              value: http
            - name: STATE_DIR_ROOT
              value: /var/lib/ks-state
          image: ' '
          name: task-processor
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/ks-state
              name: app-ks-state
      restartPolicy: Always
      volumes:
        - name: app-ks-state
          persistentVolumeClaim:
            claimName: app-ks-state
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - task-processor
        from:
          kind: ImageStreamTag
          name: task-processor:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
