debug: false
server:
  port: 8093

custom:
  security:
    provider:
      jwt:
        role:
          key: roles
        claim:
          key: realm_access

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:db1234}
  application:
    name: task-writer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://web.poc.local:8180/auth/realms/corpauth/protocol/openid-connect/certs