[http.routers]
  [http.routers.user-writer-router]
    rule = "Host(`web.poc.local`) && PathPrefix(`/api/user/writer`)"
    service = "user-writer-service"
  [http.routers.task-writer-router]
    rule = "Host(`web.poc.local`) && PathPrefix(`/api/task/writer`)"
    service = "task-writer-service"
  [http.routers.user-reader-router]
    rule = "Host(`web.poc.local`) && PathPrefix(`/api/user/reader`)"
    service = "user-reader-service"
  [http.routers.task-reader-router]
    rule = "Host(`web.poc.local`) && PathPrefix(`/api/task/reader`)"
    service = "task-reader-service"
  [http.routers.task-processor-router]
    rule = "Host(`web.poc.local`) && PathPrefix(`/api/task/processor`)"
    service = "task-processor-service"

[http.services]
  [http.services.task-writer-service]
    [[http.services.task-writer-service.loadBalancer.servers]]
      url = "http://host.docker.internal:8090"
  [http.services.user-writer-service]
    [[http.services.user-writer-service.loadBalancer.servers]]
      url = "http://host.docker.internal:8091"
  [http.services.user-reader-service]
    [[http.services.user-reader-service.loadBalancer.servers]]
      url = "http://host.docker.internal:8092"
  [http.services.task-reader-service]
    [[http.services.task-reader-service.loadBalancer.servers]]
      url = "http://host.docker.internal:8093"
  [http.services.task-processor-service]
    [[http.services.task-processor-service.loadBalancer.servers]]
      url = "http://host.docker.internal:8094"
        