version: '3'

services:
  traefik:
    command:
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/rules.toml"
      - "--providers.file.watch=true"
      - "--entrypoints.zk.address=:2181"
      - "--entrypoints.kb1.address=:19091"
      - "--entrypoints.kb2.address=:19092"
      - "--entrypoints.kb3.address=:19093"
      - "--entrypoints.appdb.address=:5432"
      - "--entrypoints.ldap.address=:389"
    volumes:
      - "./traefik/config/rules.toml:/etc/traefik/rules.toml"    
    ports:
      # Zookeeper port
      - "2181:2181"
      # Ports of Kafka broker nodes
      - "19091:19091"
      - "19092:19092"
      - "19093:19093"
      # DB instance
      - "5432:5432"
      # LDAP
      - "389:389"

  zookeeper:
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.zk.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.zk.entrypoints=zk"
      - "traefik.tcp.routers.zk.service=zk-service"
      - "traefik.tcp.services.zk-service.loadbalancer.server.port=2181"

  kafka-broker-1:
    depends_on:
      - traefik
    command: [ "zookeeper", "2181", "1", "localhost", "9091" ]
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kb1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kb1.entrypoints=kb1"
      - "traefik.tcp.routers.kb1.service=kb1-service"
      - "traefik.tcp.services.kb1-service.loadbalancer.server.port=19091"

  kafka-broker-2:
    depends_on:
      - traefik
    command: [ "zookeeper", "2181", "2", "localhost", "9092" ]
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kb2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kb2.entrypoints=kb2"
      - "traefik.tcp.routers.kb2.service=kb2-service"
      - "traefik.tcp.services.kb2-service.loadbalancer.server.port=19092"

  kafka-broker-3:
    depends_on:
      - traefik
    command: [ "zookeeper", "2181", "3", "localhost", "9093" ]
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kb3.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kb3.entrypoints=kb3"
      - "traefik.tcp.routers.kb3.service=kb3-service"
      - "traefik.tcp.services.kb3-service.loadbalancer.server.port=19093"

  appdb:
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.appdb.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.appdb.entrypoints=appdb"
      - "traefik.tcp.routers.appdb.service=appdb-service"
      - "traefik.tcp.services.appdb-service.loadbalancer.server.port=5432"

  openldap:
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ldap.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.ldap.entrypoints=ldap"
      - "traefik.tcp.routers.ldap.service=ldap-service"
      - "traefik.tcp.services.ldap-service.loadbalancer.server.port=389"