debug: false
logging:
  #file:
    #name: app.log
  level:
    root: info
    '[org.apache.kafka]': error
    '[org.springframework.kafka.config]': info
server:
  port: 8091

custom:
  security:
    provider:
      jwt:
        role:
          key: roles
        claim:
          key: realm_access

spring:
  cloud:
    stream:
      function:
        definition: output
      kafka:
        bindings:
          output-out-0:
            producer:
              messageKeyExpression: payload['id']
        binder:
          auto-create-topics: false
          autoAddPartitions: false
          brokers:
            - localhost:19091
            - localhost:19092
            - localhost:19093
          producer-properties:
            '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[schema.registry.url]': http://web.poc.local:8081
      bindings:
        output-out-0:
          destination: users
          content-type: application/*+avro
          producer:
            useNativeEncoding: true
  application:
    name: task-writer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://web.poc.local:8180/auth/realms/corpauth/protocol/openid-connect/certs