debug: false
server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskdb}
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:db1234}
  application:
    name: task-writer
                               